name: CI

on:
  pull_request:
    branches:
      - develop
      - master

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node version
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Build
        run: |
          npm i
          npm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node version
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Test
        run: |
          npm i
          npm test

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage

  coverage:
    needs: test
    runs-on: ubuntu-latest
    env:
      COMMIT_SHA: ${{ github.sha }}
      CODECOV_PROVIDER: gh
      CODECOV_TEAM: ${{ secrets.CODECOV_TEAM }}
      CODECOV_PROJECT: codecov-pipeline-fail
      CODECOV_API_TOKEN: ${{ secrets.CODECOV_API_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download coverage artifact
        uses: actions/download-artifact@v3
        with:
          name: code-coverage-report

      - name: Upload coverage
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t $CODECOV_TOKEN

      - name: Check coverage
        run: ./fail-pipeline.sh
