name: CI

on: [push]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node version
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: npm i
      - run: npm run build
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node version
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: npm i
      - run: npm test
      - run: curl -Os https://uploader.codecov.io/latest/linux/codecov
      - run: chmod +x codecov
      - run: ./codecov
